version: '3.3'

services:
    cesi:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION}"
                CONTAINER_NAME: cesi
                FROM_BASE: ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest} 
            cache_from:
                - ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.branch: $CONTAINER_GIT_BRANCH
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: cesi
        container_name: cesi
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: cesi
        image: ${DOCKER_REGISTRY:-}cesi:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
