version: '3.3'

services:
    cesi:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION}"
                CONTAINER_NAME: cesi
                FROM_BASE: ${DOCKER_REGISTRY:-}supervisord:${BASE_TAG:-latest} 
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}supervisord:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.branch: $CONTAINER_GIT_BRANCH
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: cesi
        container_name: supervisorm
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
        hostname: supervisorm
        image: ${DOCKER_REGISTRY:-}cesi/2_api:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8008:5000
            - 9008:9001
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
